# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Format Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    # - name: Get list of changed files
    #   id: changed-files
    #   run: |
    #     BASE=${{ github.event.pull_request.base.sha }}
    #     HEAD=${{ github.event.pull_request.head.sha }}
    #     CHANGED_FILES=$(git diff --name-only $BASE $HEAD)
    #     echo "changed-files=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Check format
      run: |
        git diff --name-only "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" | xargs yarn run format:check
      # env:
      #   CHANGED_FILES: ${{ env.changed-files }}
